### ISSUE TITLE
작은 코드리뷰!

### ISSUE THREAD

**Issue by dmswl2030** [flynnpark/nomad-books#1]
안녕하세요 플린님! 저두 약속한 코드리뷰 하러 날아왔습니다ㅎㅎ

### csr & ssr 같이써버리기
저희 조원들의 코드를 모두 보았는데 플린님처럼 하신분도 없었구 이렇게 `useQuery`랑 `getServerSideProps`를 같이 쓸수도 있구나? 하고
이마를 탁 치게되었습니다

같이 쓰니까 좋은점이 로딩속도, 검색엔진 최적화 등 csr과 ssr의 단점을 서로 보완해주는 것 같아요!

### 컴포넌트 분리 방식
저는 components안에 보통 각 tsx를 바로 넣어버리고 style폴더로 따로 뺸다고 생각했는데 components / Book / index.tsx, styled.ts파일 구조로 하니까 각 tsx에 맞는 스타일이다! 이게 직관적으로 보여서 좋았습니다

## 아쉬운 점
src/components/Header 폴더안에 styled.ts, styles.ts 이렇게 같은 스타일 파일이 2개가 있더라고요! 내용은 같습니다
styles.ts는 미처 정리를 못하신거 같아요!

리뷰하러 왓다가 하소연만 하는것 같지만 아직 배울점이 많아서 그런듯 합니다
작업하시느라 고생많으셧습니다!! 갓플린 최고👍

**Comment by flynnpark** [comment]
우왕 오구링님! 코드 봐주셔서 감사해요.

이번 과제는 개인적으로는 이전에 사용했던(배웠던) 기술을 계속해서 써보자~ 하는 생각으로 react-query를 써봤어요. 공식문서에서 안내하는대로 썼으니 뭐 따로 한 건 없습니다... 근데 이건 제가 강의를 안 듣고 해서 그런 것 같아요 ㅋㅋ

두 번째로 저는 오구링님 과제를를 우수작 뽑으면서 봤는데요. 오구링님 방식도 저는 꽤 좋았어요. 스타일 관련된 코드가 `styles` 폴더에 각 컴포넌트별로 있으니 잘 분리되는 느낌이었어요. 좋게 봐주셔서 감사해요.

`styles`를 분명 이름을 바꿨는데 깃 조작하는 과정에서 다시 돌아왔나봐요 ㅋㅋ 바로 삭제해버리기~~

아무튼 코드 봐주셔서 감사해요! 다음에 또 부탁드릴게요. :eyes:
